# Generated by Django 5.1.5 on 2025-04-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='free_requests',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
