# Generated by Django 5.1.5 on 2025-05-17 12:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_free_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_free_request_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='free_requests',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
