# Generated by Django 5.1.5 on 2025-02-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_completion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='content_type',
            field=models.CharField(default='image/jpeg', max_length=50),
            preserve_default=False,
        ),
    ]
