# Generated by Django 5.1.5 on 2025-04-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_completion', '0002_fileupload_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='content_type',
            field=models.CharField(max_length=150),
        ),
    ]
